server:
  port: 8080

spring:
  datasource:
    hikari:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://dev-cluv-maria-database.cnjv9cmqjlxx.ap-northeast-2.rds.amazonaws.com:3306/it1660
    username: it1660
    password: it1660

  devtools:
    livereload:
      enabled: true

  sql:
    init:
      mode: always


  thymeleaf:
    cache: false


  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB

  jpa:
    hibernate:
      default_batch_fetch_size: '1000'
      ddl-auto: create
      database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true


mybatis:
  mapper-locations: sqlmap/mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true
    multiple-result-sets-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: varchar
    default-fetch-size: 500
  type-aliases-package: com.gsitm.career




itemImgLocation: C:/shop/item

uploadPath: file:///C:/shop/
